---
title: "IGT Study Sample"
author: "Annika Kuelpmann"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_download: true
    code_folding: show
    highlight: haddock
    theme: flatly
    toc: yes
    toc_float: yes
---


```{r setup}
#| include: false

knitr::opts_chunk$set(echo = TRUE)

```

```{r packages}
#| include: false

# load R packages 
library(knitr)
library(tidyverse)
library(readxl)
library(conflicted)
library(psych)
library(kableExtra)

# declare preferences regarding conflicts 
conflicts_prefer(dplyr::filter)

```

```{r housekeeping}
#| include: false

# read procedure master file and sample categorizations
data <- read_xlsx("../../data/raw/metamethod review/master coding/codebook_procedure_master.xlsx")
samples <- read_xlsx("../../data/raw/metamethod review/master coding/codebook_categorizations.xlsx")

```

```{r functions}
#| include: false

# Defining functions used in this script

# function 1: overview over a variable
overview_variable <- function(data, variable) {
  data %>%
    select(all_of(variable)) %>%
    group_by(across(all_of(variable))) %>%
    summarise(n = n(), .groups = "drop") %>%
    mutate(percentage = round(n / sum(n) * 100, 2))
}

```

```{r data preparation}
#| include: false

# keep the first coded task per article
data <- data %>%
  distinct(article_id, .keep_all = TRUE)

# select relevant variables from data frame samples
samples <- samples %>% 
  select(article_id, category, info)

# join data with samples 
data <- data %>% 
  left_join(samples, by = "article_id")  

# create dataframe with clinical studies
data_clin <- data %>%
  filter(category == "1")

# create dataframe with non-clinical studies
data_non_clin <- data %>%
  filter(category != "1")

```

## Whole Sample
### Years of Publication
```{r total1}

# get an overview over publications years
publ_years <- overview_variable(data, "year")

publ_years |>
  kable() |>
  kable_classic(full_width = FALSE)

# range of publication years
range_publ_years <- publ_years %>%
  summarise(
    min_year = min(as.numeric(year), na.rm = TRUE),
    max_year = max(as.numeric(year), na.rm = TRUE)
  )

range_publ_years |>
  kable() |>
  kable_classic(full_width = FALSE)

```

### Sample Sizes
```{r total2}

# select sample_size and prepare for analysis 
sample_sizes <- data %>%
  select(sample_size) %>%
  filter(sample_size != "indeterminable") %>%
  unlist() %>%
  as.integer()

# summary of sample sizes across all studies
table_sample_sizes <- describe(sample_sizes)

table_sample_sizes |>
  kable() |>
  kable_classic(full_width = FALSE)

```

## Clinical Studies 
### Years of Publication
```{r clin1}

# get an overview over publications years
publ_years_clin <- overview_variable(data_clin, "year")

publ_years_clin |>
  kable() |>
  kable_classic(full_width = FALSE)

# range of publication years
range_publ_years_clin <- publ_years_clin %>%
  summarise(
    min_year = min(as.numeric(year), na.rm = TRUE),
    max_year = max(as.numeric(year), na.rm = TRUE)
  )

range_publ_years_clin |>
  kable() |>
  kable_classic(full_width = FALSE)

```

### Sample Sizes
```{r clin2}

# select sample_size and prepare for analysis 
sample_sizes_clin <- data_clin %>%
  select(sample_size) %>%
  filter(sample_size != "indeterminable") %>%
  unlist() %>%
  as.integer()

# summary of sample sizes across clinical studies
table_clinss <- describe(sample_sizes_clin)

table_clinss |>
  kable() |>
  kable_classic(full_width = FALSE)

```


### Clinical Samples
```{r clin3}

# get an overview over clinical sample types
patient_groups <- overview_variable(data_clin, "info") %>%
  arrange(info)

patient_groups |>
  kable() |>
  kable_classic(full_width = FALSE)

```


## Non-clinical Studies 
### Years of Publication
```{r nonclin1}

# get an overview over publications years
publ_years_non_clin <- overview_variable(data_non_clin, "year")

publ_years_non_clin |>
  kable() |>
  kable_classic(full_width = FALSE)

# range of publication years
range_publ_years_non_clin <- publ_years_non_clin %>%
  summarise(
    min_year = min(as.numeric(year), na.rm = TRUE),
    max_year = max(as.numeric(year), na.rm = TRUE)
  )

range_publ_years_non_clin |>
  kable() |>
  kable_classic(full_width = FALSE)

```

### Non-Clinical Samples
```{r nonclin2}

# get an overview over non-clinical sample types
other_groups <- overview_variable(data_non_clin, "info") %>%
  arrange(info)

other_groups |>
  kable() |>
  kable_classic(full_width = FALSE)

```

### Sample Sizes
```{r nonclin3}

# select sample_size and prepare for analysis 
sample_sizes_non_clin <- data_non_clin %>%
  select(sample_size) %>%
  filter(sample_size != "indeterminable") %>%
  unlist() %>%
  as.integer()

# summary of sample sizes across non-clinical studies
table_nonclinss <- describe(sample_sizes_non_clin)

table_nonclinss|>
  kable() |>
  kable_classic(full_width = FALSE)

```

## Session Info

```{r session-info}
sessionInfo()
```
