---
title: "IGT multiverse"
author: "Ian Hussey"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    code_folding: hide
    highlight: haddock
    theme: flatly
    toc: yes
    toc_float: yes
---

```{r, include=FALSE}
knitr::opts_chunk$set(message = FALSE,
                      warning = FALSE)
```

# Get data

```{r}

# dependencies
library(tidyverse)
library(knitr)
library(kableExtra)
#library(sjPlot)
#library(forcats)
library(janitor)

# function to round all numeric vars in a data frame
round_df <- function(df, n_digits = 3) {
  df %>% mutate_if(is.numeric, janitor::round_half_up, digits = n_digits)
}

# get data
load("../../data/raw/multiverse/IGTdata.rdata")

```

# Score items

## Win/loss

```{r}

data_wins <- 
  bind_rows(
    wi_100 |>
      as.tibble() |>
      rownames_to_column(var = "id") |>
      pivot_longer(cols = -id,
                   names_to = "trial",
                   values_to = "win") |>
      mutate(trial = as.numeric(str_remove(trial, "Wins_")),
             id = paste("100trials", id, sep = "_")),
    wi_95 |>
      as.tibble() |>
      rownames_to_column(var = "id") |>
      pivot_longer(cols = -id,
                   names_to = "trial",
                   values_to = "win") |>
      mutate(trial = as.numeric(str_remove(trial, "Wins_")),
             id = paste("95trials", id, sep = "_")),
    wi_150 |>
      as.tibble() |>
      rownames_to_column(var = "id") |>
      pivot_longer(cols = -id,
                   names_to = "trial",
                   values_to = "win") |>
      mutate(trial = as.numeric(str_remove(trial, "Wins_")),
             id = paste("150trials", id, sep = "_"))
  )

data_losses <- 
  bind_rows(
    lo_100 |>
      as.tibble() |>
      rownames_to_column(var = "id") |>
      pivot_longer(cols = -id,
                   names_to = "trial",
                   values_to = "loss") |>
      mutate(trial = as.numeric(str_remove(trial, "Losses_")),
             id = paste("100trials", id, sep = "_")),
    lo_95 |>
      as.tibble() |>
      rownames_to_column(var = "id") |>
      pivot_longer(cols = -id,
                   names_to = "trial",
                   values_to = "loss") |>
      mutate(trial = as.numeric(str_remove(trial, "Losses_")),
             id = paste("95trials", id, sep = "_")),
    lo_150 |>
      as.tibble() |>
      rownames_to_column(var = "id") |>
      pivot_longer(cols = -id,
                   names_to = "trial",
                   values_to = "loss") |>
      mutate(trial = as.numeric(str_remove(trial, "Losses_")),
             id = paste("150trials", id, sep = "_"))
  )

data_winloss <- 
  full_join(data_wins, data_losses, by = c("id", "trial")) |>
  # dichotomise - TODO check logic 
  mutate(balance = win + loss, 
         win_binary = ifelse(win > 50, 1, 0),  # TODO is > 50 right here?
         loss_binary = ifelse(loss < 0, 1, 0),
         advantagous = ifelse(balance > 0, 1, 0),
         disadvantagous = ifelse(balance < 0, 1, 0))

# check that no advantagous==1 & disadvantagous==1 exist
data_winloss |>
  count(advantagous, disadvantagous)

```

## Choices

This assumes 1 = A, 2 = B etc. Check against the paper?

```{r}

data_choice <- 
  bind_rows(
    choice_100 |>
      as.tibble() |>
      rownames_to_column(var = "id") |>
      pivot_longer(cols = -id,
                   names_to = "trial",
                   values_to = "choice") |>
      mutate(trial = as.numeric(str_remove(trial, "Choice_")),
             id = paste("100trials", id, sep = "_")),
    choice_95 |>
      as.tibble() |>
      rownames_to_column(var = "id") |>
      pivot_longer(cols = -id,
                   names_to = "trial",
                   values_to = "choice") |>
      mutate(trial = as.numeric(str_remove(trial, "Choice_")),
             id = paste("95trials", id, sep = "_")),
    choice_150 |>
      as.tibble() |>
      rownames_to_column(var = "id") |>
      pivot_longer(cols = -id,
                   names_to = "trial",
                   values_to = "choice") |>
      mutate(trial = as.numeric(str_remove(trial, "Choice_")),
             id = paste("150trials", id, sep = "_"))
  ) |>
  mutate(choice = as.factor(case_when(choice == 1 ~ "A",
                                      choice == 2 ~ "B",
                                      choice == 3 ~ "C",
                                      choice == 4 ~ "D")))

```

# Combine

```{r}

data_combined <- full_join(data_winloss, data_choice, by = c("id", "trial"))

```

# Score participants

## (Dis)advantagous choices

```{r}

data_scored_advantage <- data_combined |>
  group_by(id) |>
  summarize(mean_advantagous = mean(advantagous),
            mean_disadvantagous = mean(disadvantagous)) |>
  ungroup() |>
  mutate(diff = mean_advantagous - mean_disadvantagous)

data_scored_advantage |>
  select(-id) |>
  cor() |>
  round(2)

data_scored_advantage |>
  pivot_longer(cols = -id) |>
  ggplot(aes(value)) +
  geom_density() +
  facet_wrap(~name)

```

## Deck choice counts

```{r}

data_scored_decks <- data_combined |>
  group_by(id) |>
  count(choice) |>
  pivot_wider(names_from = choice,
              values_from = n) |>
  ungroup() |>
  mutate(A = ifelse(is.na(A), 0, A),
         B = ifelse(is.na(B), 0, B),
         C = ifelse(is.na(C), 0, C),
         D = ifelse(is.na(D), 0, D)) |>
  mutate(C_plus_A  = C+A,
         C_minus_A = C-A,
         D_plus_B  = D+B,
         D_minus_B = D-B,
         C_plus_D  = C+D,
         A_plus_B  = A+B,
         C_plus_D_minus_A_plus_B = C_plus_D-A_plus_B)

cors_decks <- data_scored_decks |>
  select(-id, -C) |>
  cor() |>
  round(2)

diag(cors_decks) <- NA

data_cors_modal <- tibble(cors = as.data.frame(cors_decks)$C_plus_D_minus_A_plus_B) |>
  drop_na()

ggplot(data_cors_modal, aes(cors)) +
  geom_histogram() +
  xlab("Correlation between modal scoring method and other methods")


cors_decks[lower.tri(cors_decks, diag = TRUE)] <- NA

data_cors_all <- tibble(cors = cors_decks[upper.tri(cors_decks)])

ggplot(data_cors_all, aes(cors)) +
  geom_histogram() +
  xlab("Correlation between all scores")

```

## early and late trials

```{r}

data_scored_decks_subset <- data_combined |>
  group_by(id) |>
  mutate(total_trials = max(trial),
         trial_proportion = trial/total_trials) |>
  ungroup() |>
  mutate(subset = case_when(trial_proportion <= 0.333 ~ "early",   # TODO cutoffs could be varied
                            trial_proportion >= 0.666 ~ "late")) |>
  drop_na(subset) |>
  group_by(id, subset) |>
  count(choice) |>
  pivot_wider(names_from = choice,
              values_from = n) |>
  ungroup() |>
  mutate(A = ifelse(is.na(A), 0, A),
         B = ifelse(is.na(B), 0, B),
         C = ifelse(is.na(C), 0, C),
         D = ifelse(is.na(D), 0, D)) |>
  mutate(C_plus_A  = C+A,
         C_minus_A = C-A,
         D_plus_B  = D+B,
         D_minus_B = D-B,
         C_plus_D  = C+D,
         A_plus_B  = A+B,
         C_plus_D_minus_A_plus_B = C_plus_D-A_plus_B) 

data_scored_decks_subset_wide <- data_scored_decks_subset |>
  pivot_wider(names_from = "subset",
              values_from = c(-id, -subset))

data_scored_decks_combined <- 
  full_join(data_scored_decks, 
            data_scored_decks_subset_wide,
            by = "id")

cors_decks_combined <- data_scored_decks_combined |>
  select(-id, -C, -C_early, -C_late) |>
  cor() |>
  round(2)

diag(cors_decks_combined) <- NA

data_cors_combined_modal <- tibble(cors = as.data.frame(cors_decks_combined)$C_plus_D_minus_A_plus_B) |>
  drop_na()

ggplot(data_cors_combined_modal, aes(cors)) +
  geom_histogram() +
  xlab("Correlation between modal scoring method and other methods")


cors_decks_combined[lower.tri(cors_decks_combined, diag = TRUE)] <- NA

data_cors_combined_all <- tibble(cors = cors_decks_combined[upper.tri(cors_decks_combined)])

ggplot(data_cors_combined_all, aes(cors)) +
  geom_histogram() +
  xlab("Correlation between all scores")

```

## diff/proportions between early and late

```{r}

data_scored_decks_subset_diff <- data_scored_decks_subset |>
  pivot_longer(names_to = "variable",
               values_to = "score",
               cols = c(-id, -subset)) |>
  pivot_wider(names_from = subset, 
              values_from = score) |>
  mutate(diff = late - early) |>
  select(-early, -late) |>
  pivot_wider(names_from = variable,
              values_from = diff,
              names_prefix = "diff_")
  
data_scored_decks_combined_2 <- 
  full_join(data_scored_decks_combined, 
            data_scored_decks_subset_diff,
            by = "id")

cors_decks_combined_2 <- data_scored_decks_combined_2 |>
  select(-id, -C, -C_early, -C_late, -diff_C) |>
  cor() |>
  round(2)

diag(cors_decks_combined_2) <- NA

data_cors_combined_2_modal <- 
  tibble(cors = as.data.frame(cors_decks_combined_2)$C_plus_D_minus_A_plus_B) |>
  drop_na()

ggplot(data_cors_combined_2_modal, aes(cors)) +
  geom_histogram() +
  xlab("Correlation between modal scoring method and other methods")


cors_decks_combined_2[lower.tri(cors_decks_combined_2, diag = TRUE)] <- NA

data_cors_combined_2 <- tibble(cors = cors_decks_combined_2[upper.tri(cors_decks_combined_2)])

ggplot(data_cors_combined_2, aes(cors)) +
  geom_histogram() +
  xlab("Correlation between scores")

```

# EGA

```{r}

library(EGAnet)

dat <- data_scored_decks_combined |>
  rename(A = A, 
         B = C, 
         C = C_plus_A, 
         D = C_minus_A, 
         E = C_plus_A_late, 
         F = A_late, 
         G = C_minus_A_late, 
         H = C_late, 
         
         I = C_minus_A_early, 
         J = A_early, 
         K = C_early, 
         L = C_plus_A_early, 
         
         M = D_minus_B_early, 
         N = D_early, 
         O = B_early, 
         P = D_plus_B_early, 
         Q = C_plus_D_early, 
         R = A_plus_B_early, 
         S = C_plus_D_minus_A_plus_B_early, 

         T = B, 
         U = D, 
         V = D_plus_B, 
         W = D_minus_B, 
         X = C_plus_D, 
         Y = A_plus_B, 
         Z = C_plus_D_minus_A_plus_B, 
         A1 = B_late, 
         B1 = D_late, 
         C1 = D_plus_B_late,
         D1 = D_minus_B_late,
         E1 = C_plus_D_late,
         F1 = A_plus_B_late,
         G1 = C_plus_D_minus_A_plus_B_late)

fit <- EGA(data = dat, cor = "pearson")



dat <- data_scored_decks_combined |>
  select(-id, -contains("early"), -contains("late")) 

fit <- EGA(data = dat, cor = "pearson")

```


