# Preparations

```{r}

# set working directory
setwd("../data/raw")

# load r packages
library(openxlsx)
library(psych)
library(tidyr)
library(dplyr)
library(ggplot2)
library(DescTools)
# read excel file
igtdata <- read.xlsx("igt_flex_coding.xlsx")

```


# publication years

```{r}

igtdata$year %>% 
  range()

year <- 
  igtdata$year %>% 
  table() %>% 
  data.frame() 

year <-
rename(year, years=., frequency=Freq)

```

## visualisation of publication years 

```{r}

ggplot(year, aes(years, frequency, fill=years)) + 
  geom_col() +
  scale_colour_gradient() +
  scale_x_discrete(limits=c("2002","2003","2004","2005","2006","2007","2008","2009","2010","2011",
                            "2012","2013","2014","2015","2016","2017","2018","2019","2020","2021")) +
  scale_y_discrete(limits=c(1:12)) +
  labs(x="year of publication", y="number of studies")

```


# study samples

```{r}

# bring data in a reasonable format
# create new dataframe with study samples

samples <-
igtdata$sample %>%
  data.frame()

# separate values in different columns
samples <- separate(samples, ., 
                          c("description", "category", "cat_sub"),
                          sep = ";")

# info about category: healthy sample or clinical sample
table(samples$category)

# more info about clinical samples
clinical <- subset(samples, subset = category == "clinical")
table(clinical$cat_sub)

# more info about clinical samples
healthy <- subset(samples, subset = category == "healthy")
table(healthy$cat_sub)

```


# cited IGT version

```{r}

# bring data in a reasonable format
# create new dataframe with cited version
cited_version <- data.frame(igtdata$cited)
# separate values in different columns
cited_version_sep <- separate(cited_version, igtdata.cited, 
                        c("cited1", "cited2", "cited3"),
                        sep = ";")
# create long format
cited_version_long <- pivot_longer(cited_version_sep, c(1:3), 
                                 names_to="name", values_to="citation", 
                                 values_drop_na=TRUE)
# show absolute frequencies
table(cited_version_long$citation)
# show relative frequencies (percentage)
100*prop.table(table(cited_version_long$citation))

```

