# Preparations

```{r}

# set working directory
setwd("../data/raw")

# load r packages
library(openxlsx)
library(psych)
library(tidyr)
library(dplyr)
library(ggplot2)
library(DescTools)
# read excel file
igtdata <- read.xlsx("igt_flex_coding.xlsx")

```

# modification frequencies

```{r}

# load data
attach(igtdata)
modified <- data.frame(mod_pr, mod_gls)
detach(igtdata)

# create new variable indicating any modification
modified$mod_overall <- ifelse(modified$mod_pr == 0 & modified$mod_gls == 0, "0",
                               ifelse(modified$mod_pr == 1 | modified$mod_gls == 1, "1", "-77"))
                          
# show number of modified tasks
modified$mod_overall %>%
  table()

modified$mod_pr %>%
  table()

modified$mod_gls %>%
  table()

# visualization of number of modified tasks 
modoverall <- data.frame(table(modified$mod_overall))
ggplot(modoverall, aes(Var1, Freq, fill=Var1)) +
  geom_col() + 
  scale_fill_brewer(palette="Spectral") +
  scale_x_discrete(limits=c("unclear", "unmodified", "modified")) +
  labs(x="text", y="text")

```


# cited version and modified version 

```{r}
# create dataframe
attach(igtdata)
cited_mod <- data.frame(cited, mod_pr, mod_gls)
detach(igtdata)
cited_mod_sep <- separate(cited_mod, cited, 
                              c("cited1", "cited2", "cited3"),
                              sep = ";")
cited_mod_long <- pivot_longer(cited_mod_sep, c(1:3), 
                                   names_to="name", values_to="citation", 
                                   values_drop_na=TRUE)

```


# information about payment and incentives

```{r}

## payment ##
# show absolute frequencies
igtdata$pay %<%
  table()

## start money ##
# show absolute frequencies
igtdata$start %<%
  table()

## incentives ##
# show absolute frequencies
igtdata$incent %<%
  table()

```


# information about trials 

```{r}

## number of trials ##
# show absolute frequencies
trials <- data.frame(table(igtdata$trials))
names(trials) [1] <- "trials_n"
names(trials) [2] <- "frequency"
trials

## exercise trials ##
# show absolute frequencies
table(igtdata$exercise)

## time limit for each trial ##
# show absolute frequencies
table(igtdata$time)

```


# instructions and feedback

```{r}

## goal ##
# create dataframe with goals 
goals <- data.frame(sort(table(igtdata$goal)))
goals 

## instructions ##
# create dataframe with instructions 
instructions <- data.frame(sort(table(igtdata$instruct)))
instructions

## feedback ##
# create dataframe with feedback 
feedback <- data.frame(sort(table(igtdata$feedback)))
feedback

```

# information about deck properties

```{r}

## number of decks: total, advantageous and disadvantageous ##
# show absolute frequencies
table(igtdata$decks)
table(igtdata$adv_n)
table(igtdata$disadv_n)

## number of cards per deck ##
# show absolute frequencies
table(igtdata$cards_n)

## gain and loss schedule modifications ##
table(modified$mod_gls)

```