---
title: "Inter Rater Reliability for Procedural Variations"
author: "Jan-Paul Ries"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_download: true
    code_folding: show
    highlight: haddock
    theme: flatly
    toc: yes
    toc_float: yes
---

```{r setup}
#| include: false

# load knitr 
library(knitr)

# set knitr chunk options 
opts_chunk$set(echo = TRUE,
                message = FALSE,
                warning = FALSE)
```

## Load Packages

```{r}

library(readxl)
library(dplyr)
library(irr)
library(knitr)
library(kableExtra)
library(janitor)
library(tidyverse)
library(boot)

```

# Read data 

```{r}

df_r1 <- readxl::read_xlsx("../../data/raw/interrater reliability/codebook - rater 1/r1_procedure_aligned.xlsx")
df_r2 <- readxl::read_xlsx("../../data/raw/interrater reliability/codebook - rater 2/r2_procedure_aligned.xlsx")

```

# Wrangle

Combine files with correct column order

```{r}

df_combined <- bind_cols(
  df_r1$article_id, df_r2$article_id,
  df_r1$authors, df_r2$authors,
  df_r1$year, df_r2$year,
  df_r1$order_number, df_r2$order_number,
  df_r1$sample_size, df_r2$sample_size,
  df_r1$variant, df_r2$variant,
  df_r1$protocol, df_r2$protocol,
  df_r1$goal, df_r2$goal,
  df_r1$instructions, df_r2$instructions,
  df_r1$feedback, df_r2$feedback,
  df_r1$incentives, df_r2$incentives,
  df_r1$currency, df_r2$currency,
  df_r1$starting_capital, df_r2$starting_capital,
  df_r1$reward_adv, df_r2$reward_adv,
  df_r1$reward_disadv, df_r2$reward_disadv,
  df_r1$gain1, df_r2$gain1,
  df_r1$gain2, df_r2$gain2,
  df_r1$loss1, df_r2$loss1,
  df_r1$loss2, df_r2$loss2,
  df_r1$gain_int1, df_r2$gain_int1,
  df_r1$gain_int2, df_r2$gain_int2,
  df_r1$loss_int1, df_r2$loss_int1,
  df_r1$loss_int2, df_r2$loss_int2,
  df_r1$freq_adv1, df_r2$freq_adv1,
  df_r1$freq_adv2, df_r2$freq_adv2,
  df_r1$freq_disadv1, df_r2$freq_disadv1,
  df_r1$freq_disadv2, df_r2$freq_disadv2,
  df_r1$n_blocks, df_r2$n_blocks,
  df_r1$n_trials, df_r2$n_trials,
  df_r1$notes_procedure, df_r2$notes_procedure,
  df_r1$rater_ID, df_r2$rater_ID
)

```

# Calculate Cohen's Kappa

```{r}

# Create an empty data frame to store Kappa values
kappa_results <- data.frame(Column1 = numeric(),
                               Column2 = numeric(),
                               Kappa = numeric(),
                               stringsAsFactors = FALSE)

# Loop through column pairs and calculate Cohen's Kappa
for (i in seq(1, 61, by = 2)) {
  kappa_result <- kappa2(df_combined[, c(i, i+1)])
  
  # Append results to the data frame
  kappa_results <- rbind(kappa_results, 
                            c(Column1 = i, Column2 = i+1, Kappa = kappa_result$value))
}

# add column containing column names
colnames <- colnames(df_r1)
kappa_results$col_name <- colnames

# rename column holding Kappa values
kappa_results <- kappa_results %>%
  rename(kappa = X1.1)

# delete unnecessary columns 
kappa_results <- kappa_results %>%
  dplyr::select(col_name, kappa)  

# delete unnecessary rows 
kappa_results <- kappa_results %>%
  filter(col_name != "article_id",
         col_name != "authors",
         col_name != "year",
         col_name != "order_number",
         col_name != "notes_procedure",
         col_name != "rater_ID")


```

# Tables

```{r}

kappa_results |>
  mutate_if(is.numeric, round_half_up, digits = 2) |>
  kable() |>
  kable_classic(full_width = FALSE)

kappa_results |>
  summarize(mean_kappa = mean(kappa),
            sd_kappa = sd(kappa),
            min_kappa = min(kappa),
            max_kappa = max(kappa)) |>
  mutate_if(is.numeric, round_half_up, digits = 2) |>
  kable() |>
  kable_classic(full_width = FALSE)

```

# Text in manuscript

The above results produce the results reported in the manuscript for the "Interrater reliabilty" heading. i.e., 



# How do the kappa values correspond to the indeterminability rates?
```{r}

# load data 
data <- read_xlsx("../../data/raw/metamethod review/master coding/codebook_procedure_master.xlsx") 

# create data frame with relevant variables
data_ind <- data %>%
  select(sample_size, variant, protocol,
         goal, instructions, feedback, 
         incentives, currency, starting_capital, 
         contains("reward"), contains("1"), contains("2"), 
         n_blocks, n_trials)

# count number of studies
total_studies <- nrow(data_ind)

# create indeterminables df
indeterminables <- data_ind %>%
  # create long format
  pivot_longer(cols = everything(), names_to = "variable", values_to = "value") %>%
  # filter for indeterminable values
  filter(value == "indeterminable") %>%
  # group per variable
  group_by(variable) %>%
  # count the number of distinct indeterminable values per article_id  
  summarise(count_total = n(), .groups = 'drop') %>%
  # calculate percentages 
  mutate(
    pct_total = round((count_total / total_studies * 100), 2)
  ) 

# join data frame with kappa values
joined <- kappa_results %>%
  rename(variable = col_name) %>%
  left_join(indeterminables, by = "variable") %>%
  mutate(
    count_total = replace_na(count_total, 0),
    pct_total = replace_na(pct_total, 0)
  ) %>%
  select(variable, 
         count = count_total, 
         percentage = pct_total, 
         kappa) %>%
  arrange(desc(percentage)) %>%
  mutate(across(where(is.numeric), ~ round(., digits = 2)))

# print data frame with frequency of indeterminable values 
joined |>
  kable() |>
  kable_classic(full_width = FALSE)

# filter the table to get the subset of poor reliability variables
poor_reliability_subset <- joined %>%
  filter(kappa < 0.60)

# mean percentage of indeterminables for the subset
avg_poor_irr <- mean(poor_reliability_subset$percentage)

# mean percentage of indeterminables for all variables
avg_overall <- mean(joined$percentage)

# print
print(avg_overall)
print(avg_poor_irr)

```

```{r}

# set seed
set.seed(42)

# function to estimate SE and CI 
boot_kappa <- function(data, R = 1000) {
  # calculate kappa estimate
  kappa_est <- kappa2(data)$value
  # all values are equal or NA: return directly
  if (is.na(kappa_est) || all(data[[1]] == data[[2]])) {
    return(tibble(
      kappa = round(kappa_est, 3),
      se = 0,
      ci_low = NA,
      ci_high = NA
    ))
  }
  # bootstrap function
  kappa_fun <- function(d, idx) {
    d_boot <- d[idx, ]
    kappa2(d_boot)$value
  }
  # bootstrapping
  boot_out <- boot(data = data, statistic = kappa_fun, R = R)
  # calculate SE
  se <- sd(boot_out$t)
  # caculate CI
  ci <- boot.ci(boot_out, type = "perc")$percent[4:5]
  # create tibble with data 
  tibble(
    kappa = round(kappa_est, 3),
    se = round(se, 3),
    ci_low = round(ci[1], 3),
    ci_high = round(ci[2], 3)
  )
}

# apply function
kappa_se_ci <- map_dfr(seq(1, 61, by = 2), function(i) {
  result <- boot_kappa(df_combined[, c(i, i + 1)])
  tibble(
    col_name = colnames(df_r1)[(i + 1) / 2],  
    se = result$se,
    ci_low = result$ci_low,
    ci_high = result$ci_high
  )
})

# remove variables that we dont need
kappa_se_ci <- kappa_se_ci %>%
  filter(!col_name %in% c("article_id", "authors", "year", "order_number", 
                          "notes_procedure", "rater_ID")) %>%
  # join with kappa df 
  left_join(kappa_results, by = "col_name") %>%
  select(col_name, kappa, se, ci_low, ci_high)

# print results into a table
kappa_se_ci |>
  mutate_if(is.numeric, round_half_up, digits = 2) |>
  kable() |>
  kable_classic(full_width = FALSE)

```


